// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAyunmVUqEN16uoomfRPjJpxEEKSYiyp1E',
    appId: '1:559695127958:web:caf3be9387c8c3ffe769b7',
    messagingSenderId: '559695127958',
    projectId: 'trainingpartner-58e12',
    authDomain: 'trainingpartner-58e12.firebaseapp.com',
    storageBucket: 'trainingpartner-58e12.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCEBjUoQV6xISLPSm47QsrvEymBp4YLlHQ',
    appId: '1:559695127958:android:980201f672b86266e769b7',
    messagingSenderId: '559695127958',
    projectId: 'trainingpartner-58e12',
    storageBucket: 'trainingpartner-58e12.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyATRJ_fxTRjirHN10pMCF5T6HNv4980Pfs',
    appId: '1:559695127958:ios:8f72a67a2d4127d9e769b7',
    messagingSenderId: '559695127958',
    projectId: 'trainingpartner-58e12',
    storageBucket: 'trainingpartner-58e12.appspot.com',
    iosClientId: '559695127958-aab0f1ng14jgbgi1og8dcgbk9v56k1ch.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingPartner',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyATRJ_fxTRjirHN10pMCF5T6HNv4980Pfs',
    appId: '1:559695127958:ios:87c0f5ccb658064fe769b7',
    messagingSenderId: '559695127958',
    projectId: 'trainingpartner-58e12',
    storageBucket: 'trainingpartner-58e12.appspot.com',
    iosClientId: '559695127958-v6dht8i30k1dpppgm2f14aheg37le3pb.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingPartner.RunnerTests',
  );
}
