name: training_partner
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  auth_buttons: ^3.0.2
  equatable: ^2.0.5
  animated_custom_dropdown: ^3.0.0
  expansion_tile_card: ^3.0.0
  quds_popup_menu: ^0.0.1+1
  flutter_snake_navigationbar: ^0.6.1
  fluttertoast: ^8.2.4
  google_sign_in: ^6.2.1
  lottie: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  build_runner: ^2.4.8
  flutter_staggered_animations: ^1.1.1
  http: ^1.2.0
  intl: ^0.19.0
  shimmer: ^3.0.0
  cached_network_image: ^3.3.1
  smooth_page_indicator: ^1.1.0
  font_awesome_flutter: ^10.7.0
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/animations/dumbbells.json
    - assets/csv/movements.csv
    - assets/images/default_profile_picture.jpg
    - assets/images/arms_icon.png
    - assets/images/back_icon.png
    - assets/images/cardio_icon.jpg
    - assets/images/chest_icon.png
    - assets/images/core_icon.png
    - assets/images/legs_icon.png
    - assets/images/shoulder_icon.png
    - assets/images/

  fonts:
    - family: Omnes
      fonts:
        - asset: "assets/fonts/OmnesThin.ttf"
          weight: 100
        - asset: "assets/fonts/OmnesThinItalic.ttf"
          style: italic
          weight: 100
        - asset: "assets/fonts/OmnesExtraLight.ttf"
          weight: 200
        - asset: "assets/fonts/OmnesExtraLightItalic.ttf"
          style: italic
          weight: 200
        - asset: "assets/fonts/OmnesLight.ttf"
          weight: 300
        - asset: "assets/fonts/OmnesLightItalic.ttf"
          style: italic
          weight: 300
        - asset: "assets/fonts/OmnesRegular.ttf"
          weight: 400
        - asset: "assets/fonts/OmnesItalic.ttf"
          style: italic
          weight: 400
        - asset: "assets/fonts/OmnesMedium.ttf"
          weight: 500
        - asset: "assets/fonts/OmnesMediumItalic.ttf"
          style: italic
          weight: 500
        - asset: "assets/fonts/OmnesSemiBold.ttf"
          weight: 600
        - asset: "assets/fonts/OmnesSemiBoldItalic.ttf"
          style: italic
          weight: 600
        - asset: "assets/fonts/OmnesBold.ttf"
          weight: 700
        - asset: "assets/fonts/OmnesBoldItalic.ttf"
          style: italic
          weight: 700
        - asset: "assets/fonts/OmnesBlack.ttf"
          weight: 800
        - asset: "assets/fonts/OmnesBlackItalic.ttf"
          style: italic
          weight: 800


  uses-material-design: true
